# Generated by Django 6.1.1 on 2026-09-28 13:31

import taxi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[taxi.validators.validate_license_number],
            ),
        ),
    ]
